services:
  api1: &api
    image: vitortvale/rinha-2026-ocaml:latest
    hostname: api1
    environment:
      SOCKET_PATH: /sockets/api1.sock
      DATA_DIR: /app/data
    volumes:
      - api-sockets:/sockets
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "159MB"

  api2:
    <<: *api
    hostname: api2
    environment:
      SOCKET_PATH: /sockets/api2.sock
      DATA_DIR: /app/data
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "159MB"

  haproxy:
    image: haproxy:2.9-alpine
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro,Z
      - api-sockets:/sockets
    depends_on:
      - api1
      - api2
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "32MB"

networks:
  rinha:
    driver: bridge

volumes:
  api-sockets:
