services:
  lb:
    image: ${LB_IMAGE:-vitortvale/rinha-2026-ocaml-lb:${IMAGE_TAG:-latest}}
    pull_policy: always
    command: ["/app/rinha_lb"]
    environment:
      PORT: "9999"
      UPSTREAMS: "/sockets/api1.sock,/sockets/api2.sock"
      LB_WORKERS: "32"
      BUF_SIZE: "8192"
    ports:
      - "9999:9999"
    volumes:
      - sockets:/sockets
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "32MB"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  api1:
    image: ${API_IMAGE:-vitortvale/rinha-2026-ocaml:${IMAGE_TAG:-latest}}
    pull_policy: always
    environment:
      SOCKET_PATH: "/sockets/api1.sock"
      DATA_DIR: "/app/data"
      API_WORKERS: "2"
      IVF_FAST_NPROBE: "7"
      IVF_NPROBE: "24"
      IVF_VERIFY_NPROBE: "40"
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "159MB"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    healthcheck:
      test: [ "CMD", "/app/rinha_healthcheck" ]
      interval: 5s
      timeout: 2s
      retries: 12
      start_period: 1s

  api2:
    image: ${API_IMAGE:-vitortvale/rinha-2026-ocaml:${IMAGE_TAG:-latest}}
    pull_policy: always
    environment:
      SOCKET_PATH: "/sockets/api2.sock"
      DATA_DIR: "/app/data"
      API_WORKERS: "2"
      IVF_FAST_NPROBE: "7"
      IVF_NPROBE: "24"
      IVF_VERIFY_NPROBE: "40"
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "159MB"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    healthcheck:
      test: [ "CMD", "/app/rinha_healthcheck" ]
      interval: 5s
      timeout: 2s
      retries: 12
      start_period: 1s

volumes:
  sockets:
