services:
  api1: &api
    image: vitortvale/rinha-2026-ocaml:bab7638
    pull_policy: always
    hostname: api1
    environment:
      SOCKET_PATH: /sockets/api1.sock
      DATA_DIR: /app/data
      IVF_FAST_NPROBE: "3"
      IVF_NPROBE: "24"
      RINHA_TRANSPORT: epoll
    volumes:
      - api-sockets:/sockets
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "159MB"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    healthcheck:
      test: [ "CMD", "/app/rinha_healthcheck" ]
      interval: 5s
      timeout: 2s
      retries: 12
      start_period: 1s

  api2:
    <<: *api
    hostname: api2
    environment:
      SOCKET_PATH: /sockets/api2.sock
      DATA_DIR: /app/data
      IVF_FAST_NPROBE: "3"
      IVF_NPROBE: "24"
      RINHA_TRANSPORT: epoll
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: "159MB"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  haproxy:
    image: vitortvale/rinha-2026-ocaml:bab7638
    pull_policy: always
    command: [ "/app/rinha_lb" ]
    environment:
      UPSTREAM_SOCKETS: /sockets/api1.sock,/sockets/api2.sock
    ports:
      - "9999:9999"
    volumes:
      - api-sockets:/sockets
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "32MB"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

networks:
  rinha:
    driver: bridge

volumes:
  api-sockets:
