services:
  api1:
    image: vitortvale/rinha-2026-ocaml:83d58b4
    pull_policy: always
    ports:
      - "9999:9999"
    environment:
      TCP_PORT: "9999"
      DATA_DIR: /app/data
      IVF_FAST_NPROBE: "4"
      IVF_NPROBE: "24"
    deploy:
      resources:
        limits:
          cpus: "0.999"
          memory: "344MB"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  api2:
    image: vitortvale/rinha-2026-ocaml:83d58b4
    pull_policy: always
    command: [ "sleep", "infinity" ]
    environment:
      TCP_PORT: "9998"
      DATA_DIR: /app/data
      IVF_FAST_NPROBE: "4"
      IVF_NPROBE: "24"
    deploy:
      resources:
        limits:
          cpus: "0.001"
          memory: "6MB"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
