services:
  haproxy:
    image: haproxy:2.9-alpine
    ports:
      - "9999:9999"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro,Z
      - sockets:/sockets
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.24"
          memory: "32MB"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  api1:
    image: ${API_IMAGE:-vitortvale/rinha-2026-ocaml:latest}
    environment:
      SOCKET_PATH: "/sockets/api1.sock"
      DATA_DIR: "/app/data"
      IVF_FAST_NPROBE: "4"
      IVF_NPROBE: "24"
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.38"
          memory: "159MB"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    healthcheck:
      test: [ "CMD", "/app/rinha_healthcheck" ]
      interval: 5s
      timeout: 2s
      retries: 12
      start_period: 1s

  api2:
    image: ${API_IMAGE:-vitortvale/rinha-2026-ocaml:latest}
    environment:
      SOCKET_PATH: "/sockets/api2.sock"
      DATA_DIR: "/app/data"
      IVF_FAST_NPROBE: "4"
      IVF_NPROBE: "24"
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.38"
          memory: "159MB"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    healthcheck:
      test: [ "CMD", "/app/rinha_healthcheck" ]
      interval: 5s
      timeout: 2s
      retries: 12
      start_period: 1s

volumes:
  sockets:
