(env
 (release
  (ocamlopt_flags
   (:standard
    -O3
    -rounds
    2
    -unbox-closures
    -unsafe
    -llvm-flags
    "-march=haswell -mtune=haswell"
    -flambda2-result-types-all-functions
    -flambda2-join-points
    -zero-alloc-check
    default))))

(subdir
 src
 (library
  (name rinha_lib)
  (libraries core unix)
  (modules config runtime_json time_util vectorize index linear_model))

 (executable
  (public_name rinha_api)
  (name main)
  (modules main)
  (libraries rinha_lib eio eio_main unix))

 (executable
  (public_name rinha_healthcheck)
  (name healthcheck)
  (modules healthcheck)
  (libraries unix))

 (executable
  (public_name convert_references)
  (name convert_references)
  (modules convert_references)
  (libraries core unix))

 (executable
  (public_name rinha_bench)
  (name bench)
  (modules bench)
  (libraries rinha_lib core unix)))
